---
- hosts: all
  vars:
    http_port: 8080
  remote_user: root
  tasks:
  - name: set environment variables
    lineinfile:
      dest=/home/ec2-user/settings.sh
      regexp="GOAPP_HTTPPORT=\"\""
      line="export GOAPP_HTTPPORT=\"8080\""
